language: python

sudo: false

env:
  matrix:
    - ALLOWED_HOSTS=['*']

matrix:
    fast_finish: true
    include:
      - { python: "2.7", env: DJANGO=1.11 }

      - { python: "3.4", env: DJANGO=1.11 }
      - { python: "3.4", env: DJANGO=2.0 }

      - { python: "3.5", env: DJANGO=1.11 }
      - { python: "3.5", env: DJANGO=2.0 }
      - { python: "3.5", env: DJANGO=2.1 }

      - { python: "3.6", env: DJANGO=1.11 }
      - { python: "3.6", env: DJANGO=2.0 }
      - { python: "3.6", env: DJANGO=2.1 }

      - { python: "3.7", env: DJANGO=2.0, dist: xenial, sudo: true }
      - { python: "3.7", env: DJANGO=2.1, dist: xenial, sudo: true }

install:
  - pip install tox-travis

script:
  - tox

after_success:
    - pip install codecov
    - codecov
