version: '3.5'
services:
  django:
    build:
      dockerfile: testproject/Dockerfile
      context: ..
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ../trench:/trench/trench
    ports:
      - '8000:8000'
