name: 'Build and publish to Test PyPI'

on:
  push:
    branches: [ pypi-auto-publishing ]
  pull_request:
    branches: [ pypi-auto-publishing ]

jobs:
  on-success:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - uses: actions/checkout@v2
          with:
            ref: staging
        - name: Setup Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install build
        - name: Build a binary wheel and a source tarball
          run: |
            python -m build --sdist --wheel --outdir dist/
        - name: Publish distribution to Test PyPI
          uses: pypa/gh-action-pypi-publish@release/v1.4.2
          with:
            user: __token__
            password: ${{ secrets.TEST_PYPI_API_TOKEN }}
            repository_url: https://test.pypi.org/legacy/
